import React, { useState } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import MarkMap from './markmap';
import { getAllMaps } from '../lib/api'
import Maps from '../types/maps';
import { countDataScientists, countDevelopers, countExternals, countPeople, countProduct, countTeams, countWorkingstudent } from '../utils/stringUtils';
import Card from '../components/card';
import DateFormatter from './date-formatter';

type Props = {
  allMaps: Maps[]
}

function Home({ allMaps }: Props) {
  const Component = MarkMap;
  const [currentIndex, setCurrentIndex] = useState(0);
  const currentMap = allMaps[currentIndex]

  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setCurrentIndex(parseInt(event.target.value, 10));
  };

  const marks = allMaps.map((map, index) => ({
    value: index,
    label: <DateFormatter dateString={map.date} />
  }));

  return (
    <div className={styles.container}>
      <Head>
        <title>Data Section</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-4xl font-bold my-5">
          {currentMap.title} - <DateFormatter dateString={currentMap.date} />
        </h1>
        <div className="grid grid-cols-7 gap-4 flex justify-center items-center my-5">
          <Card>
            <h2 className="text-lg font-medium"># people</h2>
            <p className="text-gray-600 mt-2">{countPeople(currentMap.content)}</p>
          </Card>
          <Card>
            <h2 className="text-lg font-medium"># teams</h2>
            <p className="text-gray-600 mt-2">{countTeams(currentMap.content)}</p>
          </Card>
          <Card>
            <h2 className="text-lg font-medium"># product</h2>
            <p className="text-gray-600 mt-2">{countProduct(currentMap.content)}</p>
          </Card>
          <Card>
            <h2 className="text-lg font-medium"># data scientists</h2>
            <p className="text-gray-600 mt-2">{countDataScientists(currentMap.content)}</p>
          </Card>
          <Card>
            <h2 className="text-lg font-medium"># developers</h2>
            <p className="text-gray-600 mt-2">{countDevelopers(currentMap.content)}</p>
          </Card>
          <Card>
            <h2 className="text-lg font-medium"># working students</h2>
            <p className="text-gray-600 mt-2">{countWorkingstudent(currentMap.content)}</p>
          </Card>
          <Card>
            <h2 className="text-lg font-medium"># externals</h2>
            <p className="text-gray-600 mt-2">{countExternals(currentMap.content)}</p>
          </Card>
        </div>
        <div>
          <input type="range" min={0} max={allMaps.length - 1} value={currentIndex} onChange={handleChange} list="tickmarks"/>
          <datalist id="tickmarks" >
            {allMaps.map((map, index) => (
              <option key={index} value={index}/>
            ))}
          </datalist>

        </div>
        <div className="flex flex-col h-screen p-2 w-full">
          <Component key={currentIndex} content={currentMap.content} handleChange={handleChange} />
        </div>

      </main>
    </div>
  );
}

export default Home

export const getStaticProps = async () => {
  const allMaps = getAllMaps([
    'title',
    'slug',
    'date',
    'content',
  ])

  return {
    props: { allMaps },
  }
}